"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var const_1 = require("./const");
exports.ModalTypes = const_1.ModalTypes;
var main_1 = require("./main");
exports.CustomModal = main_1.default;
var ducks_1 = require("./ducks");
exports.modalReducer = ducks_1.default;
exports.toggleModal = ducks_1.toggleModal;
exports.moduleName = ducks_1.moduleName;
